services:
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  server_node_modules:
  client_node_modules: